apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
  namespace: cau2
spec:
  containers:
  - name: pod1
    image: busybox:1.31.1
    command:
      - "/bin/bash"
    args: ["-c" , "while true; do echo $(date) >> /vol/date.log; sleep 5; done"]
    volumeMounts:
      - name: vol
        mountPath: /vol
  - name: pod2
    image: nginx:latest
    ports: 
    - containerPort: 80
    volumeMounts:
      - name: vol
        mountPath: /usr/share/nginx/html
  volumes:
  - name: vol 
    emptyDir: {}